import { Product } from './types'

export const sampleProducts: Product[] = [
  {
    id: '1',
    name: 'iPhone 15 Pro',
    description: 'Latest iPhone with advanced camera system and A17 Pro chip',
    price: 999,
    image: 'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=500&h=300&fit=crop',
    category: 'electronics',
    sellerId: 'seller1',
    sellerName: 'TechStore Pro',
    stock: 10,
    rating: 4.8,
    reviews: 156,
    createdAt: new Date().toISOString()
  },
  {
    id: '2',
    name: 'Nike Air Max 270',
    description: 'Comfortable running shoes with Max Air cushioning',
    price: 150,
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500&h=300&fit=crop',
    category: 'clothing',
    sellerId: 'seller2',
    sellerName: 'Sports Central',
    stock: 25,
    rating: 4.6,
    reviews: 89,
    createdAt: new Date().toISOString()
  },
  {
    id: '3',
    name: 'Organic Coffee Beans',
    description: 'Premium organic coffee beans from Colombia',
    price: 24.99,
    image: 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=500&h=300&fit=crop',
    category: 'food',
    sellerId: 'seller3',
    sellerName: 'Coffee Corner',
    stock: 50,
    rating: 4.9,
    reviews: 203,
    createdAt: new Date().toISOString()
  },
  {
    id: '4',
    name: 'Wireless Bluetooth Headphones',
    description: 'High-quality wireless headphones with noise cancellation',
    price: 199.99,
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500&h=300&fit=crop',
    category: 'electronics',
    sellerId: 'seller1',
    sellerName: 'TechStore Pro',
    stock: 15,
    rating: 4.7,
    reviews: 127,
    createdAt: new Date().toISOString()
  },
  {
    id: '5',
    name: 'Yoga Mat Premium',
    description: 'Non-slip yoga mat with carrying strap',
    price: 45,
    image: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=500&h=300&fit=crop',
    category: 'sports',
    sellerId: 'seller4',
    sellerName: 'Fitness World',
    stock: 30,
    rating: 4.5,
    reviews: 78,
    createdAt: new Date().toISOString()
  },
  {
    id: '6',
    name: 'Smart Home Speaker',
    description: 'Voice-controlled smart speaker with Alexa',
    price: 79.99,
    image: 'https://images.unsplash.com/photo-1543512214-318c7553f230?w=500&h=300&fit=crop',
    category: 'electronics',
    sellerId: 'seller1',
    sellerName: 'TechStore Pro',
    stock: 20,
    rating: 4.4,
    reviews: 94,
    createdAt: new Date().toISOString()
  },
  {
    id: '7',
    name: 'Designer Handbag',
    description: 'Luxury leather handbag with gold hardware',
    price: 299,
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=500&h=300&fit=crop',
    category: 'clothing',
    sellerId: 'seller5',
    sellerName: 'Fashion Forward',
    stock: 8,
    rating: 4.9,
    reviews: 45,
    createdAt: new Date().toISOString()
  },
  {
    id: '8',
    name: 'Garden Tool Set',
    description: 'Complete set of professional gardening tools',
    price: 89.99,
    image: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=500&h=300&fit=crop',
    category: 'home',
    sellerId: 'seller6',
    sellerName: 'Garden Paradise',
    stock: 12,
    rating: 4.6,
    reviews: 67,
    createdAt: new Date().toISOString()
  },
  {
    id: '9',
    name: 'Skincare Set',
    description: 'Complete skincare routine with natural ingredients',
    price: 65,
    image: 'https://images.unsplash.com/photo-1570194065650-d99fb4bedf0a?w=500&h=300&fit=crop',
    category: 'beauty',
    sellerId: 'seller7',
    sellerName: 'Beauty Essentials',
    stock: 40,
    rating: 4.7,
    reviews: 112,
    createdAt: new Date().toISOString()
  },
  {
    id: '10',
    name: 'Programming Book',
    description: 'Complete guide to modern web development',
    price: 49.99,
    image: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=500&h=300&fit=crop',
    category: 'books',
    sellerId: 'seller8',
    sellerName: 'Book Haven',
    stock: 35,
    rating: 4.8,
    reviews: 89,
    createdAt: new Date().toISOString()
  }
]
